import React from "react";
import { useRouter } from "next/router";
import Navbar from '@/Components/Navbar';
// import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";
import Link from "next/link";

const department = (props) => {
  // console.log(props)
  const router = useRouter();
  let d = router.query.department
  return (
    <>
     <Head>
        <title>Department-{`${d}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TopNav/> */}
      {/* <Navbar/> */}
      <div
          style={{ color: "#be6257", backgroundColor: "#efefef" }}
          className="shadow-lg text-center p-2 mb-4 my-3  rounded"
        >
          <h2><Link href="/department" ><svg className="mx-1" style={{height:"30px",width:"60px", color: "#be6257"}} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg></Link> Teacher of {`${d}`} Department</h2>
        </div>
    <div className="container">
      <div className="row">
        {props.n.map((item,index)=>{
          if(d===item.depat){
          return(<div key={index} className="card mx-2 mb-3 mt-3" style={{ width: "540px" }}>
          <div className="row g-0">
            <div className="col-md-4">
              <img
                src={item.imgurl}
                className="img-fluid p-3 rounded-start"
                alt="..."
              />
            </div>
            <div className="col-md-8">
              <div className="card-body my-3">
                <h5 className="card-title">Name: {item.name}</h5>
                <p>Desig: {item.desig}</p>
                <p>Edu: {item.edu}</p>
                <p>Depart: {item.depat}</p>
              </div>
            </div>
          </div>
        </div>)}
        }) }
      </div>
    </div>
    {/* <Footer/> */}
    </>
  );
};

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/getdepart`);
  const data = await res.json();

  return { props: data };
}

export default department;
