import AdminNav from "@/Components/AdminNav";
import Head from "next/head";
import React, { useState } from "react";

const addteacher = () => {
  const [name,setName] = useState("")
  const [desig,setDesig] = useState("")
  const [edu,setEdu] = useState("")
  const [depat,setDepart] = useState("")
  const [imgurl,setTimg] = useState("")


  const handleClick = (e)=>{
    e.preventDefault();
    // console.log(name,desig,edu,depat,timg)
    fetch("http://localhost:3000/api/addtdepart", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },

      body: JSON.stringify({name,desig,edu,depat,imgurl}),
    });
    setName("")
    setDesig("")
    setEdu("")
    setDepart("")
    setTimg("")

  }

  return (
    <>
      <Head>
        <title>Admin-Add Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminNav />
      <div className="container">
        <div
          style={{ color: "#be6257", backgroundColor: "#efefef" }}
          className="shadow-lg text-center p-2 mb-4 my-4 rounded"
        >
          <h2>Add New Teacher In Department</h2>
        </div>
        <div className="mx-5 col-sm-8">
        <form>
          <div className="form-group ">
            <label htmlFor="name" className="form-label">
              Name:
            </label>
            <input
              type="text"
              name="names"
              className="form-control"
              placeholder="Name"
              id="name"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
              }}
            />
          </div>
          <div className="form-group ">
            <label htmlFor="name" className="form-label">
              Designation
            </label>
            <input
              type="text"
              name="desig"
              className="form-control"
              placeholder="Designation"
              id="desig"
              value={desig}
              onChange={(e) => {
                setDesig(e.target.value);
              }}
            />
          </div>
          <div className="form-group ">
            <label htmlFor="name" className="form-label">
              Education
            </label>
            <input
              type="text"
              name="edu"
              className="form-control"
              placeholder="Education"
              id="edu"
              value={edu}
              onChange={(e) => {
                setEdu(e.target.value);
              }}
            />
          </div>
          <div className="form-group ">
            <label htmlFor="name" className="form-label">
              Department
            </label>
            <input
              type="text"
              name="depart"
              className="form-control"
              placeholder="Department"
              id="depart"
              value={depat}
              onChange={(e) => {
                setDepart(e.target.value);
              }}
            />
          </div>
          <div className="form-group ">
            <label htmlFor="name" className="form-label">
              Teacher Image
            </label>
            <input
              type="text"
              name="img"
              className="form-control"
              placeholder="Image URL"
              id="img"
              value={imgurl}
              onChange={(e) => {
                setTimg(e.target.value);
              }}
            />
          </div>
          <p className="text-danger"></p>
          <button
            onClick={handleClick}
            type="butten"
            className="btn btn-primary"
          >
            ADD
          </button>
        </form>
        </div>
      </div>
    </>
  );
};

export default addteacher;
