import React from "react";
import { useRouter } from 'next/router';
import Link from "next/link";
import Navbar from '@/Components/Navbar';

// import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head"; 

const news = (props) => {
  const router = useRouter();
  const q  = router.query.news;
  return (
    <>
    <Head>
        <title>News-Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img style={{}} src="../../gmgc.png" className="img-fluid" alt="..."></img>
      {/* <TopNav/> */}
      <Navbar/>
    <div className="container">
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-2 rounded"
      >
        <h2>News Detail's</h2>
      </div>
      {props.n.map((item,index)=>{
        if(q===item._id){
        return (<div key={index} className="py-2 px-5 ">
          <Link style={{"textDecoration":"blink"}} href={`/news/${item._id}`}><h5 className="text-center">{item.title}</h5></Link>
          <p className="my-4">
          {item.des}
          </p>
      </div>)}
      })}
    </div>
    <Footer/>
    </>
  );
};

export async function getServerSideProps() {
    const res = await fetch(`http://localhost:3000/api/getnews`);
    const data = await res.json();
  
    return { props: data };
  }

export default news;
