import React from "react";
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>GMGC-About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <TopNav/>
    <Navbar/>
    <div className="container">
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-3 rounded"
      >
        <h2>About Us</h2>
      </div>
      <div style={{border:"1px solid #be6257",padding:"20px"}} class="glimpsemain my-3">
        <div class="row justify-content-evenly py-3 my-2">
          <div class="col-11 col-md-5 ">
            <div class="imageGlimpse p-3">
              <img
                src="http://gmdc.edu.pk/Images/collegegate.JPG"
                class="w-100"
                alt="logoImages"
              />
            </div>
          </div>
          <div class="col-11 my-3 col-md-7">
            <div class="glimpseTExt">
              <p>
                Govt. Municipal Degree College, Faisalabad formerly called the
                Khalsa College Lyallpur, is one of the most prestigious and
                historical educational institution of the Central Punjab. it is
                a creation of Singh Sabha Movement with the purpose of providing
                quality education and awareness to the Punjabis without
                socio-religious discrimination. its historical significance
                dates back to as earlier as 1908.
              </p>
              <p>
                The foundation of Faisalabad (formerly called Lyallpur) as a new
                city was laid in 1897 and a single Govt. High School was opened
                to impart early was not sufficient to meet its continuously
                increasing educational demand. So, in 1908 some education loving
                and generous people of the city, most of whom were Sikhs.
              </p>
            </div>
          </div>
        </div>
        <div class="row justify-content-evenly py-3 ">
          <div class="col-11 col-md-7">
            <div class="glimpseTExt my-2">
              <p>
                founded this institution as a high school and named it as KHALSA
                High School Lyallpur. The piece of land for this institution was
                a gift from Sardar Jawand Singh of Chak No.213 and its
                foundation stone was laid down by Sant Bhai Attar Singh Gurmkh
                Piyara on December 25th, 1908. its building was a master-piece
                of Indian and British architecture.
              </p>
              <p>
                In 1926, the Khalsa High School was upgraded to a college. The
                inhabitants of Lyallpur and surrounding areas quenched their
                thirst for learning from this institution till the partition of
                Sub-Continent in 1947. During partition, its patrons migrated to
                Jalandhar in India and established another collegethere in
                commemoration of thier emotional association with this college
                and namedit as Lyallpur Khalsa College, Jalandhar. Both of the
                collegeshare many of thier traditions and enjoy very strong
                bilateral relations on historical, intellectual and emotional
                grounds.
              </p>
            </div>
          </div>
          <div class="col-11 col-md-5 ">
            <div class="imageGlimpse p-3">
              <img src="http://gmdc.edu.pk/Images/glimps3.JPG" class=" w-100" alt="logoImages" />
            </div>
          </div>
        </div>
        <div class="row justify-content-evenly py-3 ">
          <div class="col-11 col-md-5 ">
            <div class="imageGlimpse p-3">
              <img
                src="http://gmdc.edu.pk/Images/glimps3.JPG"
                class="ms-1 w-100"
                alt="logoImages"
              />
            </div>
          </div>
          <div class="col-11 col-md-7">
            <div class="glimpseTExt">
              <p>
                After partition, the educational activities of this college were
                suspended and its campus was converted into a refugee camp. But
                an "Anjman" tried to restore its educational activities to some
                extent in 1958. The Municipal Committee Lyallpur restarted it as
                "Intermediate Khalsa College, Lyallpur." Late on, it was
                upgraded to degree level in 1965. Subsequently, on July 1st,
                1973, it was provincialized and named as Govt. Municipal Degree
                College.
              </p>
              <p>
                Govt. Municipal Degree College, Faisalabad has the honour of
                retaining its prestigious and glorious postion through many ebbs
                and tides of history. Presently it is imparting education in
                five disciplines: Humanities, Social Sciences. Natural Sciences,
                Commerce and Computer Sciences. Offering such a vast variety
                arising from the combination of tradition and mondernity, the
                college is dedicated to produce open minded, professionally
                equipped and spiritually grounded students with an abilitiy to
                withstand the challenges of fast and competitive world and these
                aims and objectives are endorsed by the Mission Statement of the
                college.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Footer/>
    </>
  );
};

export default about;
