import React from "react";
import Navbar from "@/Components/Navbar";
import TopNav from "@/Components/TopNav";
import Footer from "@/Components/Footer";
import Head from "next/head";

const academic = () => { 

  return (
    <>
      <Head>
        <title>GMGC-Academic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
      <Navbar />
      <div className="container">
        <h1>This is academic page</h1>
      </div>
      <Footer />
    </>
  );
};

export default academic;
