import React from "react";
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";


const admission = () => {
  return (
    <>
    <Head>
        <title>GMGC-Addmission</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <Navbar/>
    <div className="container">
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-4 rounded"
      >
        <h2>Admission Process</h2>
      </div>
      <div class="my-5">
        <p className="fw-bold text-black">
          The candidate must come up to the required merit determined from time
          to time.
        </p>
        <p>
          The candidate has to appear in person for interview before the
          Admission Committee appointed by the Principal.
        </p>
        <p className="fw-bold text-black">
          The candidate has to present the following documents in original at
          the time of interview:
        </p>
        <ul>
          <li>
            Written permission from father / Guardian to seek admission to the
            college Affidavit declaring that the student will not participate in
            any political activities during college hours.
          </li>
          <li>
            Testimonials / Certificates of Boards / Universities showing marks /
            results / grade / percentage / CGPA of the last Examination(s).
          </li>
          <li>Passports size photos (3 for 1st Year), (4 for 3rd Year)</li>
          <li>
            Character Certificate / Provisional Certificate of School /
            Collegelast attended.
          </li>
          <li>N.I.C. of father.</li>
        </ul>
        <h5 className="fw-bold text-black">NOTE:</h5>
        <p>
          All the testimonials should be enclosed with the prescribed/printed
          admission form available in the prospectus. The class / qyota /
          category in which admission is sought must be clearly marked.
        </p>
      </div>
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-4 rounded"
      >
        <h2>College Uniform</h2>
      </div>
      <div class="row justify-content-evenly my-5">
        <div class="col-md-6 p-1">
          <div class="inneruniform mt-1 mx-3">
            <p>
              <strong>
                The following uniform is prescribed for the students of the
                college:
              </strong>
            </p>
            <h4>Intermediate Students:</h4>
            <p>
              <strong>Summer: </strong> Sliver grey trousers, white shirt,Blue
              Tie, black shoes.
            </p>
            <p>
              <strong>Winter: </strong> Sliver grey trousers, white shirt, Navy
              blue Blazer / jersey, black shoes.
            </p>
            <h4>
              <strong>NOTE:</strong>
            </h4>
            <p>
              Fine at the rate of Rs. 25 per day is levied on violation of the
              uniform.
            </p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="Uniform justify-content-evenly d-flex">
            <img style={{height:"300px"}}
              src="http://gmdc.edu.pk/Images/interuniform.JPG"
              class="w-50 "
              alt=""
            />
          </div>
        </div>
      </div>
      <div class="row justify-content-evenly my-5">
        <div class="col-md-6 p-1">
          <div class="inneruniform mt-2 mx-3">
            <p>
              <strong>
                The following uniform is prescribed for the students of the
                college:
              </strong>
            </p>
            <h4>BS (Hons) Students:</h4>
            <p>
              <strong>Summer: </strong> Sliver grey trousers, white shirt,Maroon
              Tie, black shoes.
            </p>
            <p>
              <strong>Winter: </strong> Sliver grey trousers, white shirt,
              Maroon Blazer / jersey, black shoes.
            </p>
            <h3>
              <strong>NOTE:</strong>
            </h3>
            <p>
              Fine at the rate of Rs. 25 per day is levied on violation of the
              uniform.
            </p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="Uniform justify-content-evenly d-flex">
            <img
              src="http://gmdc.edu.pk/Images/bsuniform.JPG"
              class="w-75 "
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
    <Footer/>
    </>
  );
};

export default admission;
