import React, { useState } from "react";
import Navbar from "@/Components/Navbar";
import TopNav from "@/Components/TopNav";
import Footer from "@/Components/Footer";
import Head from "next/head";

const contact = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const handleBot = async (e) => {
    e.preventDefault();
    // fetch("http://127.0.0.1:5000/bot", {
    //   method: "POST",
    //   headers: {
    //     "Content-Type": "application/json",
    //   },
    //   body: JSON.stringify({ name, email, message }),
    // });
    fetch("http://localhost:3000/api/addcontact", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },

      body: JSON.stringify({ name, email, message }),
    });
    setName("");
    setEmail("");
    setMessage("");
  };

  // const handleClick=(e)=>{
  //     e.preventDefault()
  //     // console.log(name,email,message)
  //     fetch("http://localhost:3000/api/addcontact", {
  //   method: "POST",
  //   headers: {
  //     "Content-Type": "application/json",
  //   },

  //   body: JSON.stringify({ name, email, message }),
  // });
  // }

  return (
    <>
      <Head>
        <title>GMGC-Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
      <Navbar />
      <div className="container">
        <div className="my-5">
          <div className="row my-5">
            <div className="col-md-6 my-3">
              <form>
                <h3>How We Can Help You?</h3>
                <div className="form-group " required="required"> 
                  <label htmlFor="name" className="form-label">
                  Name:
                </label>
                  <input
                  required
                  type="text"
                  name="names"
                  className="form-control"
                  placeholder="Name"
                  id="name"
                  value={name}
                  onChange={(e) => {
                    setName(e.target.value);
                  }}
                />
                </div>
                <p className="text-danger"></p>
                <div className="form-group ">
                  <label htmlFor="email" className="form-label">
                    Email:
                  </label>
                  <input
                    type="email"
                    name="email"
                    className="form-control"
                    placeholder="Email"
                    id="email"
                    value={email}
                    onChange={(e) => {
                      setEmail(e.target.value);
                    }}
                  />
                </div>
                <p className="text-danger"></p>
                <div className="form-group ">
                  <label htmlFor="message" className="form-label">
                    Message:
                  </label>
                  <textarea
                    name="message"
                    className="form-control w-100"
                    placeholder="Message"
                    id="Message"
                    rows="7"
                    value={message}
                    onChange={(e) => {
                      setMessage(e.target.value);
                    }}
                  ></textarea>
                </div>
                <p className="text-danger"></p>
                <button
                  onClick={handleBot}
                  type="submit"
                  className="btn btn-primary"
                >
                  Send
                </button>
              </form>
            </div>

            <div className="col-md-6 my-3">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27240.719703727915!2d73.04343938827517!3d31.411647361191402!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x392242a52bcd800b%3A0x1824e0735664b169!2sGovernment%20Municiple%20Corporation%20Despensary%20Faisalabad!5e0!3m2!1sen!2s!4v1655018954180!5m2!1sen!2s"
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                style={{ border: "0px", width: "100%", height: "100%" }}
              ></iframe>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default contact;
