import Link from "next/link";
import React from "react";
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";

const department = () => {
  return (
    <>
     <Head>
        <title>Department</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <Navbar/>
    <div className="container">
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-4 rounded"
      >
        <h2>GMGC Department's</h2>
      </div>

      <section className="pt-4 pb-5">
        <div className="container">
          <div className="col-12">
            <div className="row">
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                    Arabic
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/1arabic.png"
                  />
                  <div className="card-body">
                    <Link href="/department/arabic" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  Commerce
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/commerce.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/commerce" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  Biology
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/biology.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/biology" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  Chemistry
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/chemistry.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/chemistry" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  Computer Science
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/computer.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/computerscience" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  Economics
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/economics.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/economics" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-3 mb-3">
                <div className="card text-center">
                  <h4 style={{ color: "#be6257" }} className="card-title my-3">
                  English
                  </h4>
                  <img
                    style={{ height: "180px" }}
                    className="img-fluid p-2"
                    alt="100%x280"
                    src="https://www.gmdc.edu.pk/admin-panel/images/english.jpg"
                  />
                  <div className="card-body">
                    <Link href="/department/english" className="btn btn-primary">
                      Details
                    </Link>
                  </div>
                </div>
              </div>
         
              
            </div>
          </div>
        </div>
      </section>      
    </div>
    <Footer/>
    </>
  );
};

export default department;
