import React from 'react'
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";

const events = () => {
  return (
    <>
    <Head>
    <title>GMGC-Events</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <TopNav/>
  <Navbar/>
    <div className='container'>
      <h1>Event page</h1>
    </div>
    <Footer/>
    </>
  )
}

export default events
