import React from 'react'
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";


const gallery = () => {
  return (
    <>
    <Head>
        <title>GMGC-Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <Navbar/>
    <div className='container'>
      <div className="container">
  <div className="row">
    <div className="col-4">
    <div className="card my-5" style={{"width": "18rem"}}>
  <img src="https://www.gmdc.edu.pk/admin-panel/images/1-1675830748.jpeg" className="card-img-top" alt="..."/>
</div>
    </div>
    <div className="col-4">
    <div className="card my-5" style={{"width": "18rem"}}>
  <img src="https://www.gmdc.edu.pk/admin-panel/images/1-1675830748.jpeg" className="card-img-top" alt="..."/>
</div>
    </div>
  </div>
</div>
    </div>
    <Footer/>
    </>
  )
}

export default gallery
