// import Content from "@/Components/Content";
// import Events from "@/Components/Events";
import Footer from "@/Components/Footer";
import Imggmgc from "@/Components/Imggmgc";
import Navbar from "@/Components/Navbar";
import TopNav from "@/Components/TopNav";
import Head from "next/head";
import Link from "next/link";

export default function Home(props) {
  const arr = props.n.slice(-5).reverse();
  // let aray = arr.reverse();
  // console.log(arr)
  return (
    <>
      <Head>
        <title>GMGC-Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <Navbar/>
      <Imggmgc />
      <div className="container">
        <div className="row">
        <div className="col-sm-9">
            <figure className="my-3">
              <blockquote className="blockquote" style={{ color: "#be6257" }}>
                <h3>Muhammad Iqbal Chohan</h3>
              </blockquote>
              <figcaption className="blockquote-footer">
                Principal of <cite title="Source Title">GMGC</cite>
              </figcaption>
            </figure>
            <img
              style={{ height: "300px", width: "250px" }}
              src="https://www.gmdc.edu.pk/admin-panel/images/M%20Iqbal%20Chohan.jpg"
              className="m-3 rounded float-end"
              alt="..."
            />
            <p className="my-4">
              After serving in Education department as a teacher for a prolonged
              period of 32 years, I have nourished certain dreams and ideas in
              my mind for the training and education of our new generation and
              to enhance the standard of Government educational Institutions Now
              when I am at the twilight of my career, Allah Almighty has blessed
              me with this opportunity in the shape of my tenure as Principal to
              materialize my dreams.<br/>
              I feel the love of this college in my bones
              as I have spent my childhood as a student in this prestigious
              Institution. Right from the first day of my tenure I left no stone
              unturned in uplifting the standard of this College paying full
              attention and concentration to academics, discipline, conduct of
              classes, beautification of college, curricular and co-curricular
              activities.
              <br />
              <Link className="text-decoration-none" href="/principal">
                <span style={{ color: "#be6257" }}>Red more</span>
              </Link>
            </p>
          </div>

          <div className="col-sm-3">
            <table className="table">
              <thead>
                <tr>
                  <th scope="col" style={{ color: "#be6257" }}>
                    <h4>Latest News</h4>
                  </th>
                </tr>
              </thead>

              {arr.map((item, index) => {
                return (
                  <tbody key={index}>
                    <tr>
                      <td scope="row">
                        <Link
                          href={`/news/${item._id}`}
                          style={{ textDecoration: "blink", color: "black" }}
                        >
                          {item.title}
                          <br />
                          <span style={{ color: "#be6257" }}>Read more</span>
                        </Link>
                      </td>
                    </tr>
                  </tbody>
                );
              })}
            </table>
          </div>
        </div>
        {/* <Events /> */}

        {/* <hr/> */}
      </div>
      <Footer/>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/getnews`);
  const data = await res.json();
  return { props: data };
}
