import React from "react";
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";

const principal = () => {
  return (
    <>
     <Head>
        <title>GMGC-Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <Navbar/>
    <div className="container">
      <div className="clearfix p-4">
        <div
          style={{ color: "#be6257",backgroundColor:"#efefef" }}
          className="shadow-lg text-center p-3 mb-5 my-2 rounded"
        >
          <h2>Principal's Message</h2>
        </div>
        <img
          style={{ height: "350px", width: "280px", borderRadius: "10px" }}
          src="https://www.gmdc.edu.pk/admin-panel/images/M%20Iqbal%20Chohan.jpg"
          className="col-md-6 my-1 img-fluid float-md-end mb-5 ms-md-3"
          alt="..."
        />
        {/* <h2 style={{ color: "#be6257" }}>Principal's Message</h2> */}
        <p className="my-3">
          After serving in Education department as a teacher for a prolonged
          period of 32 years, I have nourished certain dreams and ideas in my
          mind for the training and education of our new generation and to
          enhance the standard of Government educational Institutions Now when I
          am at the twilight of my career, Allah Almighty has blessed me with
          this opportunity in the shape of my tenure as Principal to materialize
          my dreams.
        </p>
        <p>
          I feel the love of this college in my bones as I have spent my
          childhood as a student in this prestigious Institution. Right from the
          first day of my tenure I left no stone unturned in uplifting the
          standard of this College paying full attention and concentration to
          academics, discipline, conduct of classes, beautification of college,
          curricular and co-curricular activities. Now my devotion, hard work,
          labor and toil is being reflected in all the realms of college life as
          mentioned above.
        </p>
        <p>
          I advise my dear students to remain closest to your books in all the
          circumstances as sword of knowledge is stronger to the metallic sword
          and join your hands with me for lifting this College to the peaks of
          perfection. May Allah bless all of us with health and success to
          accomplish this noble cause. to the peaks of perfection.
        </p>
      </div>
      <hr />
      <div
        style={{ color: "#be6257",backgroundColor:"#efefef" }}
        className="shadow-lg text-center p-3 mb-4 my-3 rounded"
      >
        <h2>Previous Principals</h2>
      </div>
      
      <section className="pt-4 pb-5">
        <div className="container">
          <div className="row">
            <div className="col-12">
                    <div className="row">
                      <div className="col-md-4 mb-3">
                        <div className="card">
                          <img style={{height:"260px"}}
                            className="img-fluid p-2"
                            alt="100%x280"
                            src="https://www.gmdc.edu.pk/admin-panel/images/Dr%20Zahoor.jpg"
                          />
                          <div className="card-body">
                            <h4 className="card-title">Dr. Zahoor Ahmed Bhatti</h4>
                            <p className="card-text">
                             <b>DOJ:</b> 2019-04-25 <b>DOR:</b> 2022-12-31
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-4 mb-3">
                        <div className="card">
                          <img style={{height:"260px"}}
                            className="img-fluid p-2"
                            alt="100%x280"
                            src="https://www.gmdc.edu.pk/admin-panel/images/atiq.png"
                          />
                          <div className="card-body">
                            <h4 className="card-title">Muhammad Atiq Qureshi</h4>
                            <p className="card-text">
                            <b>DOJ:</b> 2018-12-07 <b>DOR:</b> 2019-04-24
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-4 mb-3">
                        <div className="card">
                          <img style={{height:"260px"}}
                            className="img-fluid p-2"
                            alt="100%x280"
                            src="https://www.gmdc.edu.pk/admin-panel/images/younes.png"
                          />
                          <div className="card-body">
                            <h4 className="card-title">Prof. Muhammad Younus</h4>
                            <p className="card-text">
                            <b>DOJ:</b> 2016-10-01 <b>DOR:</b> 2018-12-06
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-4 mb-3">
                        <div className="card">
                          <img style={{height:"260px"}}
                            className="img-fluid p-2"
                            alt="100%x280"
                            src="https://www.gmdc.edu.pk/admin-panel/images/meh.png"
                          />
                          <div className="card-body">
                            <h4 className="card-title">Prof. Mazhar Nadeem Randhawa</h4>
                            <p className="card-text">
                            <b>DOJ:</b> 2015-08-13 <b>DOR:</b> 2016-09-30
                            </p>
                          </div>
                        </div>
                      </div>
                      
                    </div>
                  </div>
                </div>
              </div>
      </section>
    </div>
    <Footer/>
    </>
  );
};

export default principal;
