import React from "react";
import Navbar from '@/Components/Navbar';
import TopNav from '@/Components/TopNav';
import Footer from "@/Components/Footer";
import Head from "next/head";


const programs = () => {
  return (
    <>
      <Head>
        <title>GMGC-Programs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <TopNav/>
    <Navbar/>
    <div className="container">
      <div
        style={{ color: "#be6257", backgroundColor: "#efefef" }}
        className="shadow-lg text-center p-2 mb-4 my-4 rounded"
      >
        <h2>GMGC Programs's</h2>
      </div>

      <div className="row my-3 ">
        <div className="col-lg-12 ">
          <div className="teachingstaffinner table-responsive">
            <table className="table table-hover  table-striped table-bordered ">
              <thead className="text-black">
                <tr>
                  <th  className="fw-bold" width="3%">Sr.#</th>
                  <th className="fw-bold" width="15%">Name</th>
                  <th className="fw-bold" width="10%">Study System</th>
                  <th className="fw-bold" width="10%">Available Time</th>
                  <th className="fw-bold" width="10%">Duration</th>
                  <th className="fw-bold" width="10%">Level</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th className="fw-bold text-black" scope="row">1</th>
                  <td>BS Computer Science</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">2</th>
                  <td>BS Physics</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">3</th>
                  <td>BS Chemistry</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">4</th>
                  <td>BS English</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">5</th>
                  <td>BS Mathematics</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">6</th>
                  <td>BS Economics</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">7</th>
                  <td>BS Urdu</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">8</th>
                  <td>BS PSYCHOLOGY</td>
                  <td>Semmester</td>
                  <td>Morning + Evenning</td>
                  <td>4 year</td>
                  <td>BS (Hon)</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">9</th>
                  <td>ICS</td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">10</th>
                  <td>F.Sc (Pre-Medical)</td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">11</th>
                  <td>F.Sc(Pre-Engineering)</td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">12</th>
                  <td>I.Com</td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">13</th>
                  <td>F.A I WITHOUT PRACTICAL SUBJEC</td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
                <tr>
                  <th className="fw-bold text-black" scope="row">14</th>
                  <td>F.A I WITH PRACTICAL SUBJECTS </td>
                  <td>Annual</td>
                  <td>Morning</td>
                  <td>2 Year's</td>
                  <td>Intermediate</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <Footer/>
    </>
  );
};

export default programs;
